config/routes.rb
MaphubPortal::Application.routes.draw do

  devise_for :admins, :users
  
  resources :users, :only => [:show, :update, :index] do 
    resources :annotations, :only => [:show, :index, :destroy]
    resources :control_points, :only => [:show, :index, :destroy]
  end
  
  resources :maps, :only => [:show, :index] do 
    resources :annotations, :only => [:create, :index, :update, :destroy]
    resources :control_points, :only => [:create, :index, :update, :destroy]
  end
  
  resources :annotations, :only => [:index, :create, :update, :show, :destroy]
  resources :control_points, :only => [:index, :show, :destroy]
  
  root :to => "home#index"

  match 'search' => 'home#search'
  match 'search/:q' => 'home#search'
  
  match 'status' => 'home#status'
  
  match "help" => 'home#help'
  match "contact" => 'home#contact'
  
  match '/maps/:map/annotations/tags' => 'annotations#tags', :as => "annotation_tag_find"
  

end

app/models/map.rb
require 'open-uri'
require 'net/http'
require 'nokogiri'
require 'ostruct'

# This class represents data about a historic map.
#
# Maps don't belong to any user. A map can have annotations and control points.

class Map < ActiveRecord::Base
  
  # Hooks  
  before_validation :has_tileset?, :extract_dimensions
  after_create :create_boundary_object
  
  # Validation
  validates_presence_of :identifier, :title, :width, :height
  
  # Model associations
  has_many :annotations, :dependent => :destroy
  has_many :control_points, :dependent => :destroy
  has_one :boundary, :as => :boundary_object, :dependent => :destroy
  accepts_nested_attributes_for :boundary
  
  # Search
  searchable do 
    text :title, :boost => 2.0
    text :subject
    text :author
    text :annotations_content, :boost => 1.0
    text :annotations_tags, :boost => 1.0
    text :annotations_enrichments, :boost => 1.0
    text :identifier
  end
  
  # Collects all annotations into a single string
  def annotations_content
    annotations.collect(&:body).join(" ")
  end
  
  # Collects all tag labels into a single string
  def annotations_tags
    tag_labels = []
    annotations.each do |annotation|
    	annotation.tags.each do |tag|
    		if tag.accepted?
      		tag_labels << tag.label
      	end
      end
    end
    tag_labels.join(" ")
  end
  
  # Collects all enrichment labels into a single string
  def annotations_enrichments
    tag_enrichments = []
    annotations.each do |annotation|
    	annotation.tags.each do |tag|
    		if tag.accepted?
      		tag_enrichments << tag.enrichment
      	end
      end
    end
    tag_enrichments.join(" ")
  end
  
  # Creates an empty boundary object for the map after creation
  def create_boundary_object
    boundary = self.build_boundary
    boundary.ne_x = self.width
    boundary.ne_y = self.height
    boundary.sw_x = 0
    boundary.sw_y = 0
    boundary.save
  end
  
  # virtual attributes
  def map_base_uri
    Rails.configuration.map_base_uri
  end
  
  def raw_image_uri
    "#{map_base_uri}/raw/#{identifier}.jp2"    
  end
  
  def tileset_uri
    "#{map_base_uri}/ts_zoomify/#{identifier}"
  end
  
  def thumbnail_uri
    "#{map_base_uri}/thumbnails/#{identifier}.jpg"
  end
  
  def thumbnail_small_uri
    "#{tileset_uri}/TileGroup0/0-0-0.jpg"
  end
  
  def image_properties_uri
    "#{tileset_uri}/ImageProperties.xml"
  end
  
  def overlay_tileset_uri
    "#{map_base_uri}/ts_google/#{identifier}"
  end
  
  def overlay_properties_uri
    "#{overlay_tileset_uri}/tilemapresource.xml"
  end
  
  def kml_uri
    "#{overlay_tileset_uri}/doc.kml"
  end
  
  # a truncated title
  def short_title
    (title.length > 50) ? title[0, 50] + "..." : title
  end
  
  # the number of control points
  def no_control_points
    self.control_points.count
  end
  
  # checks whether the overlay tileset exists
  def check_for_overlay
    url = URI.parse overlay_properties_uri
    # make a normal check for a 200 OK response
    begin
      response = Net::HTTP.get_response(url)
      self.overlay_available = (response.code == "200")
    # if there was an error during resolving ...
    rescue
      self.overlay_available = false
    end
    self.overlay_available
  end
  
  # checks whether the overlay tileset exists, without making remote queries if possible
  # this means that whenever a Google Map overlay goes offline, we won't notice
  def has_overlay?
    # if we don't know whether there's an overlay at all, do a check and return that
    if self.overlay_available.nil?
      return check_for_overlay
      
    # otherwise, return what we know already, at the risk of serving a dead link, but keeping speed
    else
      return self.overlay_available
    end
  end
  
  # checks whether the remote tileset exists
  def has_tileset?
    url = URI.parse image_properties_uri
    begin
      response = Net::HTTP.get_response(url)
      return response.code == "200"
    rescue
      false
    end
  end
  
  # Extracts image dimensions from ImageProperties.xml
  def extract_dimensions
    tileset_uri.chomp!('/') # remove trailing slash just in case
    url = URI.parse "#{tileset_uri}/ImageProperties.xml"
    response = Net::HTTP.get_response(url)
    if response.code == "200"
      self.width = response.body.match(/width="(\d*)"/i).captures.first
      self.height = response.body.match(/height="(\d*)"/i).captures.first
    end
  end
  
  # Exctracs boundary information from overlay tileset 
  def overlay_boundary
    begin
      doc = Nokogiri::XML(open(overlay_properties_uri))
    rescue
      self.overlay_available = false
      return nil
    end
    unless doc.nil?
      bounding_box = doc.xpath("//BoundingBox[@minx]")
      min_tileset = doc.xpath("//TileSets/TileSet[1]")
      max_tileset = doc.xpath("//TileSets/TileSet[last()]")

      ret = OpenStruct.new 
      ret.ne_lat = bounding_box.attribute("maxx").content
      ret.ne_lng = bounding_box.attribute("maxy").content
      ret.sw_lat = bounding_box.attribute("minx").content
      ret.sw_lng = bounding_box.attribute("miny").content
      ret.min_tileset = min_tileset.attribute("order").content
      ret.max_tileset = max_tileset.attribute("order").content
      return ret
    end
  end
  
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  
  before_filter :get_base_uri
  
  # Show all maps
  def index
    @maps = Map.order(:updated_at).page(params[:page]).per(20) 
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => Map.all }
      format.json { render :json => Map.all.to_json(:only =>[:id,:updated_at], :methods => [:no_control_points]) }
    end
  end
  
  # Render a single map
  def show
    @map = Map.find(params[:id])

    #Create 4 possible test cases with a Latin Square model
    a = 'manual-entry'
    b = 'user-suggest'
    c = 'semantic-tagging'
    d = 'semantic-tagging-wiki'
    conditions = [[a, b, d, c], [b, c, a, d], [c, d, b, a], [d, a, c, b]] 
    if(current_user != nil)

      #Assigns 4 users to each condition treatment
      condition_num = (current_user.id)%4
      
      #Creates an array to keep track of each of conditions that the user has
      #completed thus far
      assignment = []
      (0..current_user.annotations.count).each do |i|
        assignment << conditions[condition_num][i%4]
      end      
     
      #Updates the database with the completed conditions, in order of completion
      current_user.update_attribute(:condition_assignment, assignment.join(", "))

      #Starts the user on the correct condition, relative to how many annotations
      #he has already created
      annotation_num = (current_user.annotations.count)%4
      session[:condition] = conditions[condition_num][annotation_num]
     
    else
      #Condition for when user isn't logged in
      session[:condition] = 'semantic-tagging-wiki'
    end
    @current_condition = session[:condition]
    
    respond_to do |format|
      format.html # show.html.erb
      format.rdf  # show.rdf.erb
      format.kml {
        kml_data = open(@map.kml_uri).read
        send_data kml_data, :type => :kml, :filename => "#{@map.identifier}.kml"
      }
      format.json {
        map = {
          id: @map.id,
          identifier: @map.identifier,
          subject: @map.subject,
          title: @map.title,
          author: @map.author,
          date: @map.date,
          height: @map.height,
          width: @map.width,
          updated_at: @map.updated_at,
          created_at: @map.created_at,
          thumbnail_uri: @map.thumbnail_uri,
          tileset_uri: @map.tileset_uri
        }
        
        if @map.has_overlay?
          map[:overlay_tileset_uri] = @map.overlay_tileset_uri
          overlay_boundary = @map.overlay_boundary
          map[:overlay_boundary] = {
            sw_lat: overlay_boundary.sw_lat,
            sw_lng: overlay_boundary.sw_lng,
            ne_lat: overlay_boundary.ne_lat,
            ne_lng: overlay_boundary.ne_lng
          }
        end
        
        if @map.control_points.count > 0
          map[:controlpoints] = []
          @map.control_points.each do |cp|
            map[:controlpoints] << {
              lat: cp.lat,
              lng: cp.lng,
              x: cp.x,
              y: cp.y
            }
          end
        end
        
        map[:boundary] = {
          sw_lat: @map.boundary.sw_lat,
          sw_lng: @map.boundary.sw_lng,
          ne_lat: @map.boundary.ne_lat,
          ne_lng: @map.boundary.ne_lng
        }
        
        render :json => JSON.pretty_generate(map)
      }
    end
  end
      
end

app/views/maps/_carousel.html.erb
<% 
maps = Map.order("updated_at").limit(10)
%>

<div id="maps-carousel" class="carousel">
  <!-- Carousel items -->
  <div class="carousel-inner">
    <% maps.each_with_index do |map, index| %>
      <% if index == 0 %>
        <div class="active item">
      <% else %>
        <div class="item">
      <% end %>
          <center><%= link_to image_tag(map.thumbnail_uri, :alt => "#{map.title}"), map %></center>
          <div class="carousel-caption">
            <h4><%= map.title %></h4>
            <p><%= map.subject %></p>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/maps/_grid.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    $(".map-grid-image").hover(function(){
      var text = $(this).find(".preview-text-hidden").html();
      $("#preview-text").html(text);
    });
  });
</script>

<% 
unless local_assigns.has_key? :maps
  maps = Map.order("updated_at").limit(18)
end
%>

<div class="map-grid">
  <% for map in maps %>
    <div class="map-grid-image">
      <%= link_to image_tag(map.thumbnail_uri, :alt => "#{map.title}"), map %>
      <div style="display:none;" class="preview-text-hidden">
        <%= link_to map.title, map %>,
        <%= time_ago_in_words(map.created_at) %> ago
      </div>
    </div>
  <% end %>
  <br style="clear:both;">
  <p>
    <div id="preview-text">
    <!-- Here comes the preview text via JavaScript -->
    </div>
  </p>
</div>

app/views/maps/_recent.html.erb
<% 
unless local_assigns.has_key? :maps
  maps = Map.order("updated_at").limit(10).reverse()
end
%>

<ul>
  <% for map in maps %>
    <li><%= link_to map.title, map %>, <%= time_ago_in_words(map.updated_at) %> ago</li>
  <% end %>
</ul>

app/views/maps/_table_row.html.erb
<tr>
  <td class="span4">
    <%= link_to image_tag(map.thumbnail_small_uri), map %>
  </td>
  <td>
    <h3><%= link_to map.short_title, map %></h3>
  	<strong>Date</strong>: <%= map.date %><br>
  	<strong>Author</strong>: <%= map.author %><br>
    <strong>Subject</strong>: <%= map.subject %><br>
    <strong>Updated</strong>: <%= time_ago_in_words(map.updated_at) %> ago<br>
    
    <% if map.annotations.count > 0 %>
      <strong><%= pluralize(map.annotations.count, "Annotation") %></strong> (<%= link_to "show all", map_annotations_url(map) %>)
    <% end%>
  </td>
</tr>

app/views/maps/_thumbnail.html.erb
<tr>
  <td>
    <%= link_to image_tag(map.thumbnail_small_uri), map %>
  </td>
  <td valign="top">
    <h3><%= link_to map.short_title, map %></h3>
  	<strong>Date</strong>: <%= map.date %><br>
  	<strong>Author</strong>: <%= map.author %><br>
    <strong>Subject</strong>: <%= map.subject %><br>
    <strong>Updated</strong>: <%= time_ago_in_words(map.updated_at) %> ago<br>
    
    <% if map.annotations.count > 0 %>
      <strong><%= pluralize(map.annotations.count, "Annotation") %></strong> (<%= link_to "show all", map_annotations_url(map) %>)
    <% end%>
  </td>
</tr>

app/views/maps/index.html.erb
<div class="row">
  <h1>Maps</h1>
  <table class="table table-striped">
    <% @maps.each do |map| %>
      <%= render :partial => "table_row", :locals => { :map => map } %>
    <% end %>
  </table>
</div>
<div class="row">
    <div class="span12"><center><%= paginate @maps %></center></div>
</div>

app/views/maps/index.json.erb
[
<%
i = 0
@maps.each do |map|
	i = i+1
%>
{
"id": "<%= map.id %>",
"identifier": "<%= map.identifier %>",
"subject": "<%= map.subject %>",
"title": "<%= map.title %>",
"author": "<%= map.author %>",
"date": "<%= map.date %>",
"height": <%= map.height %>,
"width": <%= map.width %>,
"updated_at": "<%= map.updated_at %>",
"created_at": "<%= map.created_at %>",
"thumbnail_uri": "<%= map.thumbnail_uri %>",
"tileset_uri": "<%= map.tileset_uri %>"
<% unless map.overlay_tileset_uri.nil?%>
,"overlay_tileset_uri": "<%= map.overlay_tileset_uri %>"
<% end %>
}<% if (i < @maps.length) %>,<% end %>
<% end %>
]

app/views/maps/show.html.erb
<%= javascript_include_tag 'openlayers.js' %>
<%= javascript_include_tag '//www.google.com/jsapi' %>
<%= javascript_include_tag params[:controller] %>

<!-- Initialize OpenLayers and Google Overlay view-->
<%= javascript_tag do %>
function initOpenLayers() {
  window.annotation_view = new maphub.AnnotationView({
      width: <%= @map.width %>,
      height: <%= @map.height %>,
      zoomify_url: "<%= @map.tileset_uri + '/' %>",
      annotations_url: "<%= map_annotations_url(@map, :format => :json) %>",
      control_points_url: "<%= map_control_points_url(@map, :format => :json) %>",
      editable: <%= user_signed_in? ? "true" : "false" %>,
      user_id: <%= user_signed_in? ? current_user.id : "0" %>
  });
}

function initGoogleOverlay() {
    <% if @map.has_overlay? %>
      <% overlay_boundary = @map.overlay_boundary %>
        <% unless overlay_boundary.nil? %>
          if (typeof window.overlay_view === 'undefined') {
            window.overlay_view = new maphub.OverlayView({
              id: <%= @map.id %>,
              ne_lat: <%= overlay_boundary.ne_lat%>,
              ne_lng: <%= overlay_boundary.ne_lng%>,
              sw_lat: <%= overlay_boundary.sw_lat%>,
              sw_lng: <%= overlay_boundary.sw_lng%>,
              overlay_tileset_uri: "<%= @map.overlay_tileset_uri %>",
              min_tileset: <%= overlay_boundary.min_tileset %>,
              max_tileset: <%= overlay_boundary.max_tileset %>,
              annotations_url: "<%= map_annotations_url(@map, :format => :json) %>"
            });
          }
        <% end %>
    <% end %>
}

function initGoogleEarth(){
  <% if @map.has_overlay? %>
    if (typeof window.earth_view === 'undefined') {
      window.earth_view = new maphub.EarthView({
        kml_uri: "<%= @map.kml_uri %>"
      });
    }
  <% end %>
}

function initTaggingView() {
  <% if @current_condition == 'manual-entry' %>
    window.tagging_view = new maphub.ManualTaggingView(
      "<%= annotation_tag_find_url(:map => @map.id) %>",
      1000
    );
  <% else %>
    window.tagging_view = new maphub.TaggingView(
      "<%= annotation_tag_find_url(:map => @map.id) %>",
      1000
    );
  <% end %>
  
}

$(document).ready(function(){
  initOpenLayers();   // initialize OpenLayers by default
  initTaggingView();
  
  $("#overlay_viewer").hide();
  $("earth_viewer").hide();
  $("#googleannotation").hide();
  $("#map-type-regular").click(function() {
    $("#overlay_viewer").hide();
    $("#earth_viewer").hide();
    $("#viewer").show();
    $("#layerswitcher").show();
    $("#googleannotation").hide();
    $("#control-toggle button").removeAttr("disabled");
  });
  $("#map-type-google").click(function() {
    initGoogleOverlay();
    $("#viewer").hide();
    $("#earth_viewer").hide();
    $("#overlay_viewer").show();
    $("#layerswitcher").hide();
    $("#googleannotation").show();
    $("#control-toggle button").attr("disabled", "disabled");
    refreshGoogleAnnotation();
    removeTooltips();
    
  });
  $("#map-type-earth").click(function() {
    initGoogleEarth();
    $("#viewer").hide();
    $("#overlay_viewer").hide();
    $("#earth_viewer").show();
    $("#layerswitcher").hide();
    $("#googleannotation").hide();
    $("#control-toggle button").attr("disabled", "disabled");
    removeTooltips();
  });
});
<% end %>

<div class="row">
  <div id="tooltip-selected">
  <p id="notice"><%= notice %></p>
  
  <div class="span12">
    <div class="row">
      
      <!-- Map View -->
      <div class="span8">
        <div id="viewer" class="span8" style="height:600px;"></div>
        <div id="overlay_viewer" style="height:600px;"></div>
        <div id="earth_viewer" style="height:600px;"></div>
      </div>
      <!-- Right column-->
      <div class="span4">
        
        <h4 class="map-show-title"><%= @map.short_title %></h4>
        
        <% if user_signed_in? %>
        <div id="control-toggle">
        
          <div class="btn-group" data-toggle="buttons-radio">
            <button class="btn btn-primary" id="control-toggle-navigate" value="none">
              <i class="icon-move icon-white"></i>
              Navigate
            </button>
            <button class="btn" id="control-toggle-annotation">
              <i class="icon-pencil"></i>
              Annotate
            </button>
            <button class="btn hide" id="control-toggle-control-point" value="point">
              <i class="icon-map-marker"></i>
              Control Point
            </button>
          </div>
          <br>
        
          <div id="control-toggle-annotation-types" class="btn-group" data-toggle="buttons-radio">
            <button class="btn" value="polygon">Polygon</button>
            <button class="btn" value="line">Line</button>
            <button class="btn" value="box">Box</button>
          </div>
          <br>
        
        </div>
        
        
        <% else %>
        <div class="alert alert-info">You need to be <%= link_to 'signed in', new_user_session_path %> in order to create annotations and control points for this map!</div>
        <% end %>
        
        <% if true==false %>
        <div>

          <!--A dropdown button to toggle between Regular Map view and Google map view -->
          <div class="dropdown pull-left" id="map-type-selector">
            <button class="btn dropdown-toggle" data-toggle="dropdown" href="#map-type-selector">
              <i class="icon-eye-open"></i>
              Map View&nbsp;<b class="caret"></b>
            </button>
            <ul class="dropdown-menu">
              <li><a id="map-type-regular">Regular Map</a></li>
              <li><a id="map-type-google">Google Maps</a></li>
              <li><a id="map-type-earth">Google Earth</a></li>
            </ul>
          </div> <!--end class="dropdown"-->

          <!-- A KML download button -->
          <%= link_to map_path(@map, :format => :kml) do %>
          <div class="btn pull-left" style="margin-left:10px">
            <i class="icon-globe"></i>
            Download KML
          </div>
          <% end %>
        
        </div><br>
        <br style="clear:both;">
        <% end %>
        
        <h4>Layers</h4>
        <div id="layerswitcher"></div>
        <div id="googleannotation">
        <input type="checkbox" onClick="toggleGoogleAnnotations();" checked="checked">
            Annotations
            </div>
        <hr>
        
        <br>
        
        <strong>Title: </strong><%= @map.title %><br>
        <strong>Subject: </strong><%= @map.subject %><br>
        <strong>Author: </strong><%= @map.author %><br>
        <strong>Date: </strong><%= @map.date %>
        
        <hr>
<!-- 
        <h4>Geography</h4>
        <p>
          <strong>Control Points:</strong>
          <span id="control-points-count">
            <%= @map.control_points.count %></span>&nbsp;
            <a id="control-points-count-link" href="<%= map_control_points_url(@map) %>" style="<%= 'display:none;' if @map.control_points.count == 0 %>">
              (show all)
            </a>
        </p>
-->
      </div>
      
    </div>
  </div> 
  </div> <!-- end: #tooltip-selected -->
</div> <!-- end: .row -->

<div class="row">
  <div class="span8">
    <h3 id="annotations-header" style="<%= 'display:none;' if @map.annotations.count == 0 %>">Annotations <small><%= link_to "show all", map_annotations_path(@map) %></small></h3>
    <table class="table table-striped" id="annotation-table">
      <% for annotation in @map.annotations.order("updated_at").limit(10).reverse %>
        <%= render :partial => "annotations/single_annotation_table_row", :locals => { :annotation => annotation } %>
      <% end %>
    </table>
  </div>
</div>

<!-- Current Experiment Display 
<div class="span4 btn btn-inverse" style="position:fixed; left:0px; bottom:0px; z-index: 1000">
  <% if @current_condition == 'manual-entry' %>
    <% condition_display = 'Condition A' %>
  <% elsif @current_condition == 'user-suggest' %>
    <% condition_display = 'Condition B' %>
  <% elsif @current_condition == 'semantic-tagging' %>
    <% condition_display = 'Condition C' %>
  <% elsif @current_condition == 'semantic-tagging-wiki' %>
    <% condition_display = 'Condition D' %>
  <% end %>
  
  <p><%= condition_display %></p>
</div>
-->
<!-- Modal dialogs -->

<div class="modal hide" id="modal-annotation">
  <div class="modal-header">
      <a class="close" data-dismiss="modal" onclick="window.tagging_view.reset();">×</a>
      <h3>Add Annotation</h3>
  </div>
  <% @annotation = Annotation.new %>
  <%= form_for([@map, @annotation], :remote => true ) do |f| %>
    <div class="modal-body">
      <p>
        <%= f.text_area :body, :cols => 80, :rows => 10, :style => "width: 500px" %>
      </p>
      <%= f.text_field :wkt_data, :style => "display:none" %>
      <% @boundary = @annotation.build_boundary %>
      <%= f.fields_for :boundary do |b| %>
        <%= b.text_field :ne_x, :style => "display:none" %>
        <%= b.text_field :ne_y, :style => "display:none" %>
        <%= b.text_field :sw_x, :style => "display:none" %>
        <%= b.text_field :sw_y, :style => "display:none" %>
      <% end %>
      <h4>Tags</h4>
      <% if @current_condition == 'manual-entry' %><!-- Manual entry conditional -->
          <p>
            Add tags here (separated by commas)
            <%= f.text_area :condition, :cols => 80, :rows => 2, 
            :style => "width: 500px", :id => "manual-tag-entry" %>
          </p>   
      <% end %> <!--End manual entry conditional-->
      <% if @current_condition != 'manual-entry' %><!-- Manual entry conditional -->
        <span><%= image_tag "progress-dots.gif", :style => "display: none;", :id => 'loading-tags' %></span>
      <% end %> <!--End manual entry conditional-->
        <div id="modal-annotation-tags" class="tags-list">
          
        </div>
        
        <br style="clear: both;">
        <% if @current_condition != 'manual-entry' %><!-- Manual entry conditional -->
          <div id="modal-annotation-help">
            <div id='no-tags' style="display: none;"><em>Add some text to generate matching tags for this annotation &hellip;</em></div>
            <div id='tagging-help' style="display: none;"><em>Click on a tag to accept it. Click once more to reject it.</em></div>
            
          </div>
        </div>
       <% end %>
       
    <%= f.hidden_field :condition, :value => @current_condition %>
    <div class="modal-footer">
      <%= f.submit "Save annotation", :class => "btn btn-primary", :id => "annotation-submit-button", :disable_with => 'Saving...' %>
    </div>
  <% end %>
</div>

<div class="modal hide" id="modal-control-point">
  <div class="modal-header">
      <a class="close" data-dismiss="modal">×</a>
      <h3>Add Control Point</h3>
    </div>
    <%= form_for([@map, ControlPoint.new], :remote => true, :class => 'floatLeft') do |f| %>
         
      <%= f.text_field :name, :style => "display:none" %>
      <%= f.text_field :geonames_id, :style => "display:none" %>
      <%= f.text_field :geonames_label, :style => "display:none" %>
      <%= f.text_field :lat, :style => "display:none" %>
      <%= f.text_field :lng, :style => "display:none" %>
      <%= f.text_field :x, :style => "display:none" %>
      <%= f.text_field :y, :style => "display:none" %>
      <%= f.text_field :wkt_data, :style => "display:none" %>
      <div class="modal-body">
        <p>Enter a location that belongs to this point: <br/>
        <input name="place-search" id="place-search" size="40"/></p>
      </div>
      <div class="modal-footer">
        <%= f.submit "Save control point", :class => "btn btn-primary", :disable_with => 'Saving...' %>
      </div>
    <% end %>
</div>

app/views/maps/show.rdf.erb
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dcterms="http://purl.org/dc/terms/">
  <rdf:Description rdf:about="<%= @base_uri %>">
    <dcterms:identifier><%= @map.identifier %></dcterms:identifier>
    <dcterms:title><%= @map.title %></dcterms:title>
    <dcterms:subject><%= @map.subject %></dcterms:subject>
  </rdf:Description>
</rdf:RDF>