config/routes.rb
MaphubPortal::Application.routes.draw do

  devise_for :admins, :users
  
  resources :users, :only => [:show, :update, :index] do 
    resources :annotations, :only => [:show, :index, :destroy]
    resources :control_points, :only => [:show, :index, :destroy]
  end
  
  resources :maps, :only => [:show, :index] do 
    resources :annotations, :only => [:create, :index, :update, :destroy]
    resources :control_points, :only => [:create, :index, :update, :destroy]
  end
  
  resources :annotations, :only => [:index, :create, :update, :show, :destroy]
  resources :control_points, :only => [:index, :show, :destroy]
  
  root :to => "home#index"

  match 'search' => 'home#search'
  match 'search/:q' => 'home#search'
  
  match 'status' => 'home#status'
  
  match "help" => 'home#help'
  match "contact" => 'home#contact'
  
  match '/maps/:map/annotations/tags' => 'annotations#tags', :as => "annotation_tag_find"
  

end

app/controllers/home_controller.rb
require 'open-uri'
require 'net/http'
require 'timeout'

class HomeController < ApplicationController

  def search
    
    @q = params[:q]
    
    @search = Map.search do
      keywords params[:q]
    end
    
    @results = @search.results
    
    @results = Kaminari.paginate_array(@results).page(params[:page]).per(20)
    
    respond_to do |format|
      format.html # search.html.erb
      format.xml  { render :xml => @results }
    end
    
  end
  
  def status
    
    @status = {
      maps:       {
        description: "Map resources and tilesets",
        url: Rails.configuration.map_base_uri,
        status: test_status(Rails.configuration.map_base_uri)
      },
      geonames: {
        description: "GeoNames lookup service",
        url: Rails.configuration.geoname_query,
        status: test_status(Rails.configuration.geoname_query)
      },
      wikipedia: {
        description: "Wikipedia Miner lookup service",
        url: Rails.configuration.wikipedia_miner_uri,
        status: test_status(Rails.configuration.wikipedia_miner_uri)
      },
      dbpedia: {
        description: "DBpedia SPARQL request service",
        url: Rails.configuration.dbpedia_sparql_uri,
        status: test_status(Rails.configuration.dbpedia_sparql_uri)
      }
    }
    
    respond_to do |format|
      format.html # status.html.erb
      format.xml { render :xml => @status }
      format.json { render :json => @status }
    end
  end
  
  # tests the status for a given URL
  def test_status(test_url)
    begin
      url = URI.parse(test_url)
      ret = ""
      begin
        timeout = Timeout::timeout(Rails.configuration.remote_timeout) {
          ret = Net::HTTP.get_response(url).code
        }
      rescue Timeout::Error
        logger.warn("#{test_url} timed out after #{Rails.configuration.remote_timeout} seconds.")
        return :unavailable
      end
      puts "#{test_url} returns #{ret}."
      status = (["200", "301", "302", "400"].include? ret) ? :available : :unavailable
      puts status
    rescue Exception => e
      puts "#{test_url} raises error #{e}"
      status = :unavailable
    end
    status
  end

end

app/views/home/contact.html.erb
<h1>Contact us</h1>

<ul>
  <li>Our website is <a href="http://maphub.github.com/">maphub.github.com</a>.</li>
  <li>Please file any bug reports in <a href="https://github.com/maphub/maphub-portal/issues?state=open">the issue tracker</a>.</li>
  <li>If you want to leave feedback, use the button labeled <strong>feedback</strong> in the lower right corner.</li>
</ul>

app/views/home/help.html.erb
<h1>Help</h1>

If you need help using maphub, please watch our screencast at the <a href="http://maphub.github.com">maphub homepage</a>.

app/views/home/index.html.erb
<!-- <header>
    <div class="hero-unit">
        <p class="lead">View and annotate maps in the Library of Congress Historic Map Collection!</p>
    </div>
</header> -->

<div class="row">
    <div class="span8 offset2" id="top-main">
        <%= render :partial => "maps/carousel" %>        
    </div>
</div>
    
<div class="row">
    <div class="span4">
      <h2 class="first-headers">Top Contributors</h2>
      <%= render :partial => "users/top_contributors" %>
    </div>
    <div class="span4">
      <h2 class="first-headers">Annotations <small><%= link_to "show all", annotations_url %></small></h2>
      <%= render :partial => "annotations/recent" %>
    </div>
    <div class="span4">
      <h2 class="first-headers">Control Points <small><%= link_to "show all", control_points_url %></small></h2>
      <%= render :partial => "control_points/recent" %>
    </div>
</div>
    

app/views/home/search.html.erb
<div class="row">
  <div class="span12">
  
  <h1>Search Results <small>Your search for "<%= @q %>" returned <%= @search.results.length %> results.</small></h1>
  
  <% if @results.length > 0 %>
    <div class="row">
      <div class="span12">
        <table class="table table-striped">
        <% for map in @results %>
          <%= render :partial => "maps/table_row", :locals => { :map => map } %>
        <% end %>
        </table>
      </div>
    </div>
  <% end %>
  
  </div>
</div>
<div class="row">
    <div class="span12"><center><%= paginate @results %></center></div>
</div>

app/views/home/status.html.erb
<div class="row">
  <h1>Service Status</h1>
</div>

<div class="row">
  <table class="table table-striped span10">
    <thead>
      <tr>
        <th>Service</th>
        <th>Description</th>
        <th>URL</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @status.each do |key, val| %>
        <tr>
          <td><strong><%= key %></strong></td>
          <td><%= val[:description] %></td>
          <td><code><%= link_to val[:url], val[:url] %></code></td>
          <td>
            <% status = val[:status] %>
            <div class="alert alert-<%= (status == :available) ? 'success' : 'error' %>">
              <i class="icon icon-<%= (status == :available) ? 'ok' : 'remove' %>"></i>
              <%= status %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>