config/routes.rb
MaphubPortal::Application.routes.draw do

  devise_for :admins, :users
  
  resources :users, :only => [:show, :update, :index] do 
    resources :annotations, :only => [:show, :index, :destroy]
    resources :control_points, :only => [:show, :index, :destroy]
  end
  
  resources :maps, :only => [:show, :index] do 
    resources :annotations, :only => [:create, :index, :update, :destroy]
    resources :control_points, :only => [:create, :index, :update, :destroy]
  end
  
  resources :annotations, :only => [:index, :create, :update, :show, :destroy]
  resources :control_points, :only => [:index, :show, :destroy]
  
  root :to => "home#index"

  match 'search' => 'home#search'
  match 'search/:q' => 'home#search'
  
  match 'status' => 'home#status'
  
  match "help" => 'home#help'
  match "contact" => 'home#contact'
  
  match '/maps/:map/annotations/tags' => 'annotations#tags', :as => "annotation_tag_find"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>maphub portal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/default.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>maphub</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
<!--    
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
-->
    <!-- Le JS -->
    <%= javascript_include_tag "application" %>
    
    <!-- Google Web Fonts -->
    <%= google_webfonts_link_tag "Architects Daughter" %>
    <%= google_webfonts_link_tag "Gentium Basic" %>
    
    <!-- Search feature -->
    <script type="text/javascript">
      $(document).ready(function(){
        <% if @q.nil? %>
          var activeSearch = false;
          var searchBoxDefault = "Search maphub...";  
        <% else %>
          var activeSearch = true;
          var searchBoxDefault = "<%= @q %>";
          
        <% end %>

        $("#searchbox").attr("value", searchBoxDefault);

        // show/hide default text if needed
        $("#searchbox").focus(function(){
          if (($(this).attr("value") == searchBoxDefault) && (!activeSearch))
            $(this).attr("value", "");
        });
        $("#searchbox").blur(function(){
          if ($(this).attr("value") == "") 
            $(this).attr("value", searchBoxDefault);
        });
      });
    </script>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="brand" href="/"><strong>maphub</strong></a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li class="<%= 'active' if params[:controller] == "maps" %>"><%= link_to "maps", maps_path  %></li>
              <li class="<%= 'active' if params[:controller] == "users" %>"><%= link_to "users", users_path  %></li>
            </ul>
            <%= form_tag search_path, :method => 'get', :class => "navbar-search" do %>
              <%= text_field_tag :q, params[:q], :id => "searchbox", :class => "search-qurey", :size => "40" %>
            <% end %>
            <ul class="nav pull-right" id="right-nav">
                <% if not user_signed_in? %>
                    <li><%= link_to 'Log in', new_user_session_path %></li>
                    <li><%= link_to 'Sign up', new_user_registration_path %></li>
                <% end %>
                <% if user_signed_in? -%>
                <li style="padding-bottom:-10px">

                </li>
                    <li>
                      <%= link_to current_user do %>
                        <%= image_tag(current_user.gravatar_url(:size => 20)) %>&nbsp;&nbsp;
                        <%= current_user.username %>
                      <% end %>
                    </li>
                    <li>
                      <%= link_to edit_user_registration_path do  %>
                        <i class="icon-user icon-white"></i>&nbsp;&nbsp;my account
                      <% end %>
                    </li>
                    <li>
                      <%= link_to destroy_user_session_path, :method => :delete do %>
                        <i class="icon-remove icon-white"></i>&nbsp;&nbsp;sign out
                      <% end %>
                    </li>
                <% end -%>
                <% if admin_signed_in? -%>
                    <li><%= current_admin.username %></li>
                    <li><%= link_to 'admin area', admins_path %></li>
                    <li><%= link_to 'sign out', destroy_admin_session_path %></li>
                <% end -%>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <%= yield %>
      </div>
      <footer>
        
        <p>Maphub is being developed at <a href="http://www.infosci.cornell.edu/" title="Cornell University - Information Science - Overview">Cornell Information Science</a>, with support from the <a href="http://illinois.edu/" title="University of Illinois at Urbana-Champaign">University of Illinois at Urbana-Champaign</a> and the <a href="http://www.univie.ac.at/en/" title="University of Vienna">University of Vienna</a>.</p>
          <p>This work is supported by the <a href="http://www.openannotation.org/" title="Welcome">Open Annotation Collaboration</a> through a generous grant from the <a href="http://www.mellon.org/" title="About the Foundation &mdash; The Andrew W. Mellon Foundation">Andrew W. Mellon Foundation</a>. It is licensed under a <a href="http://creativecommons.org/licenses/by-sa/3.0/" title="Creative Commons &mdash; Attribution-ShareAlike 3.0 Unported
            &mdash; CC BY-SA 3.0">Creative Commons Attribution-Share Alike 3.0 Unported License</a>.</p>
          <p>All software is distributed under the <a href="http://www.apache.org/licenses/LICENSE-2.0.html" title="Apache License, Version 2.0">Apache License, Version 2.0</a>.</p>
        
        <p><a href="/contact">contact</a> | <a href="/help">help</a> | <a href="/status">service status</a></p>
       </footer>
    </div> <!-- /container -->
    
    

  </body>
</html>